// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmIheG7Gr1dNkj7vLq_Ye8oQIwYv8a2Fk',
    appId: '1:419629765662:web:cec859ba80db3c67e30a0f',
    messagingSenderId: '419629765662',
    projectId: 'todo-44746',
    authDomain: 'todo-44746.firebaseapp.com',
    storageBucket: 'todo-44746.appspot.com',
    measurementId: 'G-E38J65GQQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByMccjZp6E__OsylPTJ6m-t1fOfYiZQ1w',
    appId: '1:419629765662:android:1a93e71e04b73abce30a0f',
    messagingSenderId: '419629765662',
    projectId: 'todo-44746',
    storageBucket: 'todo-44746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaBCyqxWMRWYtPW2ZQj2OnL-KR9BZrZVE',
    appId: '1:419629765662:ios:d09a245b25fd9482e30a0f',
    messagingSenderId: '419629765662',
    projectId: 'todo-44746',
    storageBucket: 'todo-44746.appspot.com',
    iosClientId: '419629765662-n1rcmh57cbol82g6irmqt4s4ln373uk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaBCyqxWMRWYtPW2ZQj2OnL-KR9BZrZVE',
    appId: '1:419629765662:ios:6cd1fa14555fb231e30a0f',
    messagingSenderId: '419629765662',
    projectId: 'todo-44746',
    storageBucket: 'todo-44746.appspot.com',
    iosClientId: '419629765662-vrb5g23ta7tg9anlgadj43vrlpsllr7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopingApp.RunnerTests',
  );
}
